plugins {
    id 'java'
    id 'maven-publish'
}

group = 'org.apache.logging.log4j'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'
    implementation 'org.yaml:snakeyaml:2.2'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = 'org.apache.logging.log4j'
            artifactId = 'rlog4j-all-platforms'
            version = '0.1.0-SNAPSHOT'
        }
    }
}
